trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      whoami
      pwd
      ls -la /home/azureuser
      ls -la /home/azureuser/devops-webapp
      cd /home/azureuser/devops-webapp
      pwd
      git status
    readyTimeout: '20000'