trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'Azure-VM-SSH'
    runOptions: 'inline'
    inline: |
      cd /home/azureuser/azure-devops-docker-project

      docker build -t azure-web .

      docker stop azure-container || true
      docker rm azure-container || true

      docker run -d --name azure-container -p 80:80 azure-web

    readyTimeout: '20000'