trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      pwd
      whoami
      ls -la
      ls -la /home/azureuser
      ls -la /home/azureuser/devops-webapp
    readyTimeout: '20000'