trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'Azure-VM-SSH'
    runOptions: 'commands'
    commands: |
      cd ~/azure-devops-docker-project
      git pull origin main
      docker build -t azure-web .
      docker stop azure-container || true
      docker rm azure-container || true
      docker run -d --name azure-container -p 80:80 azure-web
    readyTimeout: '20000'